language: python
python:
  - "2.7"
#  - "3.3"
#  - "3.4"
#  - "3.5"
install:
  - "pip install pyyaml"
  - "python ./setup.py install"
script: 
  - murmgr
  - murmgr -y new_repository R
  - murmgr -y -r R new_package abc
  - murmgr -y -r R new_package def
  - murmgr -y -r R show

